version: "3.8"

services:
  my_db:
    image: mongo:latest
    container_name: my_db_container
    restart: always
   
 
  my_app:
    build: .
    container_name: my_app_container
    ports:
      - 3001:4000
    environment:
      PORT: ${PORT}
      DB_URI_REMOTE: ${DB_URI_REMOTE}
      DB_URI: ${DB_URI}

    depends_on:
      - my_db
    volumes:
      - ./src:/app/src
   
